version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/go/amechan/src
    command: realize start --run --no-config
    ports:
      - 8080:80
    environment:
      - MYSQL_HOST_NAME=db
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/initdb:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci